import type {
  User,
  Resume,
  JobMatch,
  Application,
  ATSScore,
} from "@/lib/db/types";

const dummyUsers: User[] = [
  {
    userId: "user-001",
    email: "alex.johnson@gmail.com",
    displayName: "Alex Johnson",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-11-15T10:30:00Z",
    lastLoginAt: "2026-03-05T14:22:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 3,
      totalJobsApplied: 12,
      averageATSScore: 82,
    },
  },
  {
    userId: "user-002",
    email: "sarah.williams@gmail.com",
    displayName: "Sarah Williams",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-10-20T09:15:00Z",
    lastLoginAt: "2026-03-04T16:45:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 2,
      totalJobsApplied: 8,
      averageATSScore: 75,
    },
  },
  {
    userId: "user-003",
    email: "michael.chen@gmail.com",
    displayName: "Michael Chen",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-12-01T11:00:00Z",
    lastLoginAt: "2026-03-06T08:30:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 1,
      totalJobsApplied: 5,
      averageATSScore: 88,
    },
  },
  {
    userId: "user-004",
    email: "jessica.martinez@gmail.com",
    displayName: "Jessica Martinez",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-09-10T13:25:00Z",
    lastLoginAt: "2026-03-05T10:10:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 4,
      totalJobsApplied: 15,
      averageATSScore: 79,
    },
  },
  {
    userId: "user-005",
    email: "david.kumar@gmail.com",
    displayName: "David Kumar",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-11-05T14:40:00Z",
    lastLoginAt: "2026-03-06T12:00:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 2,
      totalJobsApplied: 10,
      averageATSScore: 85,
    },
  },
  {
    userId: "user-006",
    email: "emma.smith@gmail.com",
    displayName: "Emma Smith",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-10-08T15:50:00Z",
    lastLoginAt: "2026-03-03T11:20:00Z",
    profileComplete: false,
    metadata: {
      totalResumesUploaded: 1,
      totalJobsApplied: 3,
      averageATSScore: 72,
    },
  },
  {
    userId: "user-007",
    email: "robert.thompson@gmail.com",
    displayName: "Robert Thompson",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-08-20T10:15:00Z",
    lastLoginAt: "2026-03-06T09:45:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 3,
      totalJobsApplied: 18,
      averageATSScore: 81,
    },
  },
  {
    userId: "user-008",
    email: "laura.patel@gmail.com",
    displayName: "Laura Patel",
    role: "job_seeker",
    isJobSeeker: true,
    createdAt: "2025-11-12T12:30:00Z",
    lastLoginAt: "2026-03-02T14:15:00Z",
    profileComplete: true,
    metadata: {
      totalResumesUploaded: 2,
      totalJobsApplied: 7,
      averageATSScore: 86,
    },
  },
];

const dummyResumes: Resume[] = [
  {
    resumeId: "resume-001",
    userId: "user-001",
    uploadedAt: "2025-11-20T10:00:00Z",
    lastModifiedAt: "2026-02-15T14:30:00Z",
    parsedData: {
      personalInfo: {
        name: "Alex Johnson",
        email: "alex.johnson@gmail.com",
        phone: "(555) 123-4567",
        location: "San Francisco, CA",
        linkedin: "linkedin.com/in/alexjohnson",
        portfolio: "alexjohnson.dev",
      },
      skills: [
        { skillName: "React", category: "Frontend", proficiency: "expert" },
        { skillName: "TypeScript", category: "Languages", proficiency: "expert" },
        { skillName: "Node.js", category: "Backend", proficiency: "intermediate" },
        { skillName: "Next.js", category: "Frontend", proficiency: "expert" },
        { skillName: "PostgreSQL", category: "Database", proficiency: "intermediate" },
        { skillName: "Tailwind CSS", category: "Frontend", proficiency: "expert" },
        { skillName: "API Design", category: "Backend", proficiency: "intermediate" },
        { skillName: "Docker", category: "DevOps", proficiency: "beginner" },
      ],
      experience: [
        {
          company: "Tech Innovations Inc.",
          position: "Senior Frontend Developer",
          startDate: "2023-03-01",
          endDate: "present",
          description: "Lead frontend development for customer-facing applications",
          achievements: [
            "Improved application performance by 40%",
            "Mentored 3 junior developers",
            "Architected new component library",
          ],
        },
        {
          company: "Digital Solutions Ltd.",
          position: "Full Stack Developer",
          startDate: "2021-06-15",
          endDate: "2023-02-28",
          description: "Developed and maintained web applications",
          achievements: [
            "Built REST APIs serving 1M+ requests daily",
            "Reduced deployment time by 60%",
            "Implemented automated testing pipeline",
          ],
        },
      ],
      education: [
        {
          institution: "Stanford University",
          degree: "Bachelor of Science",
          field: "Computer Science",
          graduationDate: "2021-05-15",
          gpa: "3.8",
        },
      ],
      certifications: [
        {
          name: "AWS Certified Solutions Architect",
          issuer: "Amazon Web Services",
          dateObtained: "2023-09-10",
        },
      ],
      projects: [
        {
          name: "AI-Powered Analytics Dashboard",
          description: "Real-time data visualization dashboard",
          technologies: ["React", "TypeScript", "D3.js"],
          url: "https://github.com/alexjohnson/analytics-dashboard",
        },
      ],
    },
    aiAnalysis: {
      strengthAreas: ["Strong technical foundation", "Great communication skills", "Leadership experience"],
      improvementAreas: ["Cloud architecture", "Mobile development"],
      suggestedJobRoles: ["Senior Frontend Developer", "Full Stack Engineer", "Tech Lead"],
      overallQuality: 92,
    },
  },
  {
    resumeId: "resume-002",
    userId: "user-002",
    uploadedAt: "2025-10-25T11:30:00Z",
    lastModifiedAt: "2026-02-20T10:15:00Z",
    parsedData: {
      personalInfo: {
        name: "Sarah Williams",
        email: "sarah.williams@gmail.com",
        phone: "(555) 234-5678",
        location: "New York, NY",
        linkedin: "linkedin.com/in/sarahwilliams",
      },
      skills: [
        { skillName: "Python", category: "Languages", proficiency: "expert" },
        { skillName: "Data Analysis", category: "Analytics", proficiency: "expert" },
        { skillName: "SQL", category: "Database", proficiency: "expert" },
        { skillName: "Machine Learning", category: "AI/ML", proficiency: "intermediate" },
        { skillName: "Tableau", category: "Visualization", proficiency: "intermediate" },
        { skillName: "Excel", category: "Tools", proficiency: "expert" },
        { skillName: "Business Intelligence", category: "Analytics", proficiency: "expert" },
        { skillName: "Pandas", category: "Libraries", proficiency: "expert" },
      ],
      experience: [
        {
          company: "DataCorp Analytics",
          position: "Senior Data Analyst",
          startDate: "2022-01-10",
          endDate: "present",
          description: "Lead data analysis initiatives and drive insights",
          achievements: [
            "Discovered 5 revenue opportunities worth $2M+",
            "Built automated reporting systems",
            "Trained 4 analysts on best practices",
          ],
        },
        {
          company: "Financial Services Group",
          position: "Data Analyst",
          startDate: "2020-07-01",
          endDate: "2021-12-31",
          description: "Analyzed financial data and created dashboards",
          achievements: [
            "Created 20+ Tableau dashboards",
            "Reduced report generation time by 75%",
            "Identified $500K cost savings",
          ],
        },
      ],
      education: [
        {
          institution: "UC Berkeley",
          degree: "Master of Science",
          field: "Statistics",
          graduationDate: "2020-05-20",
        },
        {
          institution: "UC Berkeley",
          degree: "Bachelor of Science",
          field: "Mathematics",
          graduationDate: "2018-05-15",
        },
      ],
      certifications: [],
      projects: [
        {
          name: "Customer Churn Prediction Model",
          description: "ML model predicting customer attrition",
          technologies: ["Python", "scikit-learn", "pandas"],
        },
      ],
    },
    aiAnalysis: {
      strengthAreas: ["Exceptional analytical skills", "Data visualization expertise", "Statistical knowledge"],
      improvementAreas: ["Programming skills", "Cloud platforms"],
      suggestedJobRoles: ["Senior Data Analyst", "Data Scientist", "Analytics Manager"],
      overallQuality: 88,
    },
  },
  {
    resumeId: "resume-003",
    userId: "user-003",
    uploadedAt: "2025-12-05T13:45:00Z",
    lastModifiedAt: "2026-03-01T09:20:00Z",
    parsedData: {
      personalInfo: {
        name: "Michael Chen",
        email: "michael.chen@gmail.com",
        phone: "(555) 345-6789",
        location: "Seattle, WA",
        linkedin: "linkedin.com/in/michaelchen",
      },
      skills: [
        { skillName: "Kubernetes", category: "DevOps", proficiency: "expert" },
        { skillName: "Docker", category: "DevOps", proficiency: "expert" },
        { skillName: "AWS", category: "Cloud", proficiency: "expert" },
        { skillName: "Terraform", category: "IaC", proficiency: "intermediate" },
        { skillName: "Python", category: "Languages", proficiency: "intermediate" },
        { skillName: "Golang", category: "Languages", proficiency: "intermediate" },
        { skillName: "CI/CD", category: "DevOps", proficiency: "expert" },
        { skillName: "Linux", category: "Systems", proficiency: "expert" },
      ],
      experience: [
        {
          company: "Cloud Systems Corp",
          position: "DevOps Engineer",
          startDate: "2023-06-01",
          endDate: "present",
          description: "Manage cloud infrastructure and deployment pipelines",
          achievements: [
            "Reduced deployment time from 2 hours to 15 minutes",
            "Implemented Kubernetes cluster for 100+ microservices",
            "Achieved 99.99% uptime SLA",
          ],
        },
        {
          company: "StartupXYZ",
          position: "Infrastructure Engineer",
          startDate: "2021-09-15",
          endDate: "2023-05-31",
          description: "Built scalable infrastructure for high-traffic applications",
          achievements: [
            "Designed multi-region AWS architecture",
            "Reduced infrastructure costs by 40%",
            "On-boarded 50+ developers to new platform",
          ],
        },
      ],
      education: [
        {
          institution: "University of Washington",
          degree: "Bachelor of Science",
          field: "Computer Engineering",
          graduationDate: "2021-06-10",
        },
      ],
      certifications: [
        {
          name: "Certified Kubernetes Administrator",
          issuer: "Linux Foundation",
          dateObtained: "2024-03-15",
        },
        {
          name: "AWS Certified Solutions Architect - Professional",
          issuer: "Amazon Web Services",
          dateObtained: "2023-12-20",
        },
      ],
      projects: [
        {
          name: "Multi-Region Kubernetes Platform",
          description: "Global Kubernetes platform",
          technologies: ["Kubernetes", "Terraform", "AWS"],
        },
      ],
    },
    aiAnalysis: {
      strengthAreas: ["DevOps expertise", "Infrastructure design", "Cloud platform mastery"],
      improvementAreas: ["Application development", "Team management"],
      suggestedJobRoles: ["Senior DevOps Engineer", "Cloud Architect", "Infrastructure Lead"],
      overallQuality: 94,
    },
  },
  {
    resumeId: "resume-004",
    userId: "user-004",
    uploadedAt: "2025-09-18T09:00:00Z",
    lastModifiedAt: "2026-02-25T15:40:00Z",
    parsedData: {
      personalInfo: {
        name: "Jessica Martinez",
        email: "jessica.martinez@gmail.com",
        phone: "(555) 456-7890",
        location: "Austin, TX",
        linkedin: "linkedin.com/in/jessicamartinez",
      },
      skills: [
        { skillName: "Project Management", category: "Management", proficiency: "expert" },
        { skillName: "Agile/Scrum", category: "Methodology", proficiency: "expert" },
        { skillName: "Stakeholder Management", category: "Communication", proficiency: "expert" },
        { skillName: "Budget Planning", category: "Finance", proficiency: "intermediate" },
        { skillName: "Risk Management", category: "Management", proficiency: "expert" },
        { skillName: "Team Leadership", category: "Leadership", proficiency: "expert" },
        { skillName: "Jira", category: "Tools", proficiency: "expert" },
        { skillName: "Salesforce", category: "Tools", proficiency: "intermediate" },
      ],
      experience: [
        {
          company: "Enterprise Solutions Inc.",
          position: "Program Manager",
          startDate: "2022-03-01",
          endDate: "present",
          description: "Lead complex technology programs and teams",
          achievements: [
            "Managed $10M+ program budget",
            "Delivered 5 major initiatives on-time",
            "Led team of 15 across 3 departments",
          ],
        },
        {
          company: "Tech Startup Hub",
          position: "Project Manager",
          startDate: "2019-11-01",
          endDate: "2022-02-28",
          description: "Managed product development and deployment projects",
          achievements: [
            "Launched 3 successful products",
            "Reduced project delivery time by 30%",
            "Managed budgets up to $2M",
          ],
        },
      ],
      education: [
        {
          institution: "Texas A&M University",
          degree: "Bachelor of Business Administration",
          field: "Project Management",
          graduationDate: "2019-05-15",
        },
      ],
      certifications: [
        {
          name: "PMP",
          issuer: "Project Management Institute",
          dateObtained: "2021-06-10",
        },
        {
          name: "Certified Scrum Master",
          issuer: "Scrum Alliance",
          dateObtained: "2020-09-20",
        },
      ],
      projects: [],
    },
    aiAnalysis: {
      strengthAreas: ["Project management expertise", "Leadership capabilities", "Strategic thinking"],
      improvementAreas: ["Technical knowledge", "Product sense"],
      suggestedJobRoles: ["Director of Project Management", "Program Manager", "Product Manager"],
      overallQuality: 90,
    },
  },
  {
    resumeId: "resume-005",
    userId: "user-005",
    uploadedAt: "2025-11-10T14:20:00Z",
    lastModifiedAt: "2026-02-28T11:35:00Z",
    parsedData: {
      personalInfo: {
        name: "David Kumar",
        email: "david.kumar@gmail.com",
        phone: "(555) 567-8901",
        location: "Boston, MA",
        linkedin: "linkedin.com/in/davidkumar",
      },
      skills: [
        { skillName: "Java", category: "Languages", proficiency: "expert" },
        { skillName: "Spring Boot", category: "Framework", proficiency: "expert" },
        { skillName: "Microservices", category: "Architecture", proficiency: "expert" },
        { skillName: "PostgreSQL", category: "Database", proficiency: "expert" },
        { skillName: "REST APIs", category: "Backend", proficiency: "expert" },
        { skillName: "System Design", category: "Architecture", proficiency: "intermediate" },
        { skillName: "Git", category: "Tools", proficiency: "expert" },
        { skillName: "Maven", category: "Build Tools", proficiency: "intermediate" },
      ],
      experience: [
        {
          company: "Enterprise Software Co.",
          position: "Lead Backend Engineer",
          startDate: "2022-05-15",
          endDate: "present",
          description: "Design and implement backend systems",
          achievements: [
            "Architected microservices handling 10K RPS",
            "Improved API latency by 50%",
            "Mentored 5 engineers",
          ],
        },
        {
          company: "FinTech Innovations",
          position: "Backend Developer",
          startDate: "2020-02-01",
          endDate: "2022-04-30",
          description: "Developed financial transaction processing systems",
          achievements: [
            "Built payment processing system handling $100M+ annually",
            "Implemented ACID compliance features",
            "Reduced database query time by 65%",
          ],
        },
      ],
      education: [
        {
          institution: "MIT",
          degree: "Master of Science",
          field: "Computer Science",
          graduationDate: "2020-05-22",
        },
        {
          institution: "IIT Delhi",
          degree: "Bachelor of Technology",
          field: "Computer Science",
          graduationDate: "2018-05-18",
        },
      ],
      certifications: [],
      projects: [
        {
          name: "Real-time Event Processing System",
          description: "High-throughput event streaming",
          technologies: ["Java", "Kafka", "Spring Boot"],
        },
      ],
    },
    aiAnalysis: {
      strengthAreas: ["Backend architecture", "System design", "Code quality"],
      improvementAreas: ["Frontend development", "Mobile development"],
      suggestedJobRoles: ["Senior Backend Engineer", "Architect", "Technical Lead"],
      overallQuality: 91,
    },
  },
  {
    resumeId: "resume-006",
    userId: "user-006",
    uploadedAt: "2025-10-12T10:45:00Z",
    lastModifiedAt: "2026-02-10T13:20:00Z",
    parsedData: {
      personalInfo: {
        name: "Emma Smith",
        email: "emma.smith@gmail.com",
        phone: "(555) 678-9012",
        location: "Chicago, IL",
      },
      skills: [
        { skillName: "UI/UX Design", category: "Design", proficiency: "expert" },
        { skillName: "Figma", category: "Tools", proficiency: "expert" },
        { skillName: "User Research", category: "Research", proficiency: "intermediate" },
        { skillName: "Wireframing", category: "Design", proficiency: "expert" },
        { skillName: "Design Systems", category: "Design", proficiency: "intermediate" },
        { skillName: "Prototyping", category: "Design", proficiency: "expert" },
        { skillName: "Adobe XD", category: "Tools", proficiency: "intermediate" },
        { skillName: "Accessibility", category: "Design", proficiency: "intermediate" },
      ],
      experience: [
        {
          company: "Creative Agency Pro",
          position: "UX/UI Designer",
          startDate: "2021-08-01",
          endDate: "present",
          description: "Design user experiences for web and mobile applications",
          achievements: [
            "Designed interfaces used by 500K+ users",
            "Improved user satisfaction score from 72% to 89%",
            "Led design system implementation",
          ],
        },
      ],
      education: [
        {
          institution: "School of the Art Institute of Chicago",
          degree: "Bachelor of Fine Arts",
          field: "Graphic Design",
          graduationDate: "2021-05-20",
        },
      ],
      certifications: [],
      projects: [
        {
          name: "E-Commerce Platform Redesign",
          description: "Complete UX/UI redesign",
          technologies: ["Figma", "Prototyping"],
        },
      ],
    },
    aiAnalysis: {
      strengthAreas: ["Design creativity", "User-centric thinking"],
      improvementAreas: ["Technical skills", "Cross-functional collaboration"],
      suggestedJobRoles: ["Senior UX/UI Designer", "Design Lead", "Product Designer"],
      overallQuality: 75,
    },
  },
  {
    resumeId: "resume-007",
    userId: "user-007",
    uploadedAt: "2025-08-25T12:10:00Z",
    lastModifiedAt: "2026-02-20T16:50:00Z",
    parsedData: {
      personalInfo: {
        name: "Robert Thompson",
        email: "robert.thompson@gmail.com",
        phone: "(555) 789-0123",
        location: "Denver, CO",
        linkedin: "linkedin.com/in/robertthompson",
      },
      skills: [
        { skillName: "C++", category: "Languages", proficiency: "expert" },
        { skillName: "Systems Programming", category: "Development", proficiency: "expert" },
        { skillName: "Algorithm Design", category: "CS Fundamentals", proficiency: "expert" },
        { skillName: "Performance Optimization", category: "Development", proficiency: "expert" },
        { skillName: "Python", category: "Languages", proficiency: "intermediate" },
        { skillName: "Linux", category: "Systems", proficiency: "expert" },
        { skillName: "Network Programming", category: "Systems", proficiency: "intermediate" },
        { skillName: "Debugging", category: "Development", proficiency: "expert" },
      ],
      experience: [
        {
          company: "High Performance Computing Inc.",
          position: "Senior Systems Engineer",
          startDate: "2019-03-01",
          endDate: "present",
          description: "Develop high-performance computing systems",
          achievements: [
            "Optimized computation pipeline, 3x performance improvement",
            "Led development of core library used company-wide",
            "Mentored 2 junior engineers",
          ],
        },
        {
          company: "Gaming Studio XYZ",
          position: "Game Engine Programmer",
          startDate: "2017-06-15",
          endDate: "2019-02-28",
          description: "Developed game engine systems",
          achievements: [
            "Implemented physics engine",
            "Optimized memory usage by 40%",
            "Shipped 2 AAA titles",
          ],
        },
      ],
      education: [
        {
          institution: "University of Colorado",
          degree: "Bachelor of Science",
          field: "Computer Science",
          graduationDate: "2017-05-15",
        },
      ],
      certifications: [],
      projects: [],
    },
    aiAnalysis: {
      strengthAreas: ["Low-level programming", "Performance expertise", "Systems knowledge"],
      improvementAreas: ["Web development", "Frontend skills"],
      suggestedJobRoles: ["Senior Systems Engineer", "Performance Engineer", "Technical Architect"],
      overallQuality: 89,
    },
  },
  {
    resumeId: "resume-008",
    userId: "user-008",
    uploadedAt: "2025-11-15T15:30:00Z",
    lastModifiedAt: "2026-02-28T12:45:00Z",
    parsedData: {
      personalInfo: {
        name: "Laura Patel",
        email: "laura.patel@gmail.com",
        phone: "(555) 890-1234",
        location: "San Jose, CA",
        linkedin: "linkedin.com/in/laurapatel",
      },
      skills: [
        { skillName: "Product Management", category: "Management", proficiency: "expert" },
        { skillName: "Market Research", category: "Research", proficiency: "expert" },
        { skillName: "Data Analysis", category: "Analytics", proficiency: "intermediate" },
        { skillName: "User Testing", category: "Research", proficiency: "expert" },
        { skillName: "Roadmapping", category: "Strategy", proficiency: "expert" },
        { skillName: "Cross-functional Leadership", category: "Leadership", proficiency: "expert" },
        { skillName: "SQL", category: "Tools", proficiency: "intermediate" },
        { skillName: "A/B Testing", category: "Analytics", proficiency: "intermediate" },
      ],
      experience: [
        {
          company: "SaaS Leader Corp",
          position: "Senior Product Manager",
          startDate: "2021-07-01",
          endDate: "present",
          description: "Lead product strategy and development",
          achievements: [
            "Grew user base from 10K to 500K",
            "Increased product revenue by 250%",
            "Managed 3 concurrent product initiatives",
          ],
        },
        {
          company: "Mobile App Startup",
          position: "Product Manager",
          startDate: "2019-01-15",
          endDate: "2021-06-30",
          description: "Owned product roadmap and strategy",
          achievements: [
            "Launched 2 major product features",
            "Achieved 4.8 star app rating",
            "Grew DAU by 150%",
          ],
        },
      ],
      education: [
        {
          institution: "Harvard Business School",
          degree: "MBA",
          field: "Business Administration",
          graduationDate: "2019-05-23",
        },
        {
          institution: "Cornell University",
          degree: "Bachelor of Science",
          field: "Economics",
          graduationDate: "2017-05-29",
        },
      ],
      certifications: [
        {
          name: "Pragmatic Marketing Certified",
          issuer: "Pragmatic Institute",
          dateObtained: "2021-09-15",
        },
      ],
      projects: [],
    },
    aiAnalysis: {
      strengthAreas: ["Product vision", "Market understanding", "Leadership"],
      improvementAreas: ["Technical depth", "Engineering knowledge"],
      suggestedJobRoles: ["VP Product", "Senior Product Manager", "Chief Product Officer"],
      overallQuality: 93,
    },
  },
];

const dummyJobMatches: JobMatch[] = [
  {
    jobMatchId: "match-001",
    userId: "user-001",
    resumeId: "resume-001",
    jobDetails: {
      title: "Senior Frontend Engineer",
      company: "Tech Giants Inc.",
      location: "San Francisco, CA",
      jobType: "full-time",
      experienceLevel: "senior",
      salary: { min: 180000, max: 220000, currency: "USD" },
      description: "Looking for a senior frontend engineer with React expertise",
      requirements: ["5+ years React", "TypeScript", "System design"],
      responsibilities: ["Lead frontend architecture", "Mentoring", "Code reviews"],
      benefits: ["Health insurance", "401k", "Remote options"],
      sourceUrl: "https://example.com/job1",
      postedDate: "2026-02-20T10:00:00Z",
    },
    matchScore: 94,
    matchedSkills: ["React", "TypeScript", "Next.js", "System Design"],
    missingSkills: [],
    fetchedAt: "2026-02-20T10:00:00Z",
    isBookmarked: true,
    status: "applied",
  },
  {
    jobMatchId: "match-002",
    userId: "user-002",
    resumeId: "resume-002",
    jobDetails: {
      title: "Data Scientist - AI/ML",
      company: "AI Innovations Lab",
      location: "New York, NY",
      jobType: "full-time",
      experienceLevel: "senior",
      salary: { min: 160000, max: 200000, currency: "USD" },
      description: "Looking for experienced data scientist",
      requirements: ["3+ years ML", "Python", "Statistical modeling"],
      responsibilities: ["Build ML models", "Data analysis", "Research"],
      benefits: ["Stock options", "Research budget"],
      sourceUrl: "https://example.com/job2",
      postedDate: "2026-02-18T14:30:00Z",
    },
    matchScore: 88,
    matchedSkills: ["Python", "Data Analysis", "ML", "SQL"],
    missingSkills: ["Deep Learning frameworks"],
    fetchedAt: "2026-02-18T14:30:00Z",
    isBookmarked: false,
    status: "applied",
  },
  {
    jobMatchId: "match-003",
    userId: "user-003",
    resumeId: "resume-003",
    jobDetails: {
      title: "DevOps Lead",
      company: "Cloud Infrastructure Pro",
      location: "Seattle, WA",
      jobType: "full-time",
      experienceLevel: "senior",
      salary: { min: 170000, max: 210000, currency: "USD" },
      description: "Lead DevOps team and cloud strategy",
      requirements: ["Kubernetes", "AWS", "CI/CD"],
      responsibilities: ["Team leadership", "Infrastructure design", "Mentoring"],
      benefits: ["Flexible hours", "Learning budget"],
      sourceUrl: "https://example.com/job3",
      postedDate: "2026-02-15T09:00:00Z",
    },
    matchScore: 96,
    matchedSkills: ["Kubernetes", "AWS", "Docker", "CI/CD"],
    missingSkills: [],
    fetchedAt: "2026-02-15T09:00:00Z",
    isBookmarked: true,
    status: "applied",
  },
  {
    jobMatchId: "match-004",
    userId: "user-004",
    resumeId: "resume-004",
    jobDetails: {
      title: "Program Manager - Product",
      company: "Enterprise Tech Corp",
      location: "Austin, TX",
      jobType: "full-time",
      experienceLevel: "senior",
      salary: { min: 150000, max: 190000, currency: "USD" },
      description: "Lead product and engineering programs",
      requirements: ["5+ years PM", "Agile", "Stakeholder management"],
      responsibilities: ["Program leadership", "Roadmap", "Cross-team coordination"],
      benefits: ["Bonus potential", "Remote flexibility"],
      sourceUrl: "https://example.com/job4",
      postedDate: "2026-02-17T11:20:00Z",
    },
    matchScore: 91,
    matchedSkills: ["Project Management", "Agile", "Leadership", "Stakeholder Management"],
    missingSkills: ["Technical background"],
    fetchedAt: "2026-02-17T11:20:00Z",
    isBookmarked: false,
    status: "applied",
  },
];

const dummyApplications: Application[] = [
  {
    applicationId: "app-001",
    userId: "user-001",
    resumeId: "resume-001",
    jobMatchId: "match-001",
    appliedAt: "2026-02-22T10:15:00Z",
    finalATSScore: 94,
    applicationStatus: "interview",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-22T10:15:00Z" },
      { status: "screening", updatedAt: "2026-02-24T14:30:00Z" },
      { status: "interview", updatedAt: "2026-02-28T11:00:00Z" },
    ],
    interviewDetails: [
      {
        round: 1,
        type: "phone",
        scheduledAt: "2026-03-05T14:00:00Z",
        completedAt: "2026-03-05T14:30:00Z",
        feedback: "Great communication skills, strong technical background",
      },
    ],
    notes: "Candidate showed excellent performance in phone interview",
  },
  {
    applicationId: "app-002",
    userId: "user-002",
    resumeId: "resume-002",
    jobMatchId: "match-002",
    appliedAt: "2026-02-20T09:45:00Z",
    finalATSScore: 88,
    applicationStatus: "screening",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-20T09:45:00Z" },
      { status: "screening", updatedAt: "2026-02-25T16:20:00Z" },
    ],
    interviewDetails: [],
    notes: "Resume review in progress",
  },
  {
    applicationId: "app-003",
    userId: "user-003",
    resumeId: "resume-003",
    jobMatchId: "match-003",
    appliedAt: "2026-02-18T13:30:00Z",
    finalATSScore: 96,
    applicationStatus: "offer",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-18T13:30:00Z" },
      { status: "screening", updatedAt: "2026-02-20T10:00:00Z" },
      { status: "interview", updatedAt: "2026-02-25T15:45:00Z" },
      { status: "offer", updatedAt: "2026-03-02T09:30:00Z" },
    ],
    interviewDetails: [
      {
        round: 1,
        type: "technical",
        scheduledAt: "2026-02-25T14:00:00Z",
        completedAt: "2026-02-25T15:45:00Z",
        feedback: "Outstanding technical knowledge and architecture understanding",
      },
    ],
    notes: "Offer extended at $200K base + equity",
  },
  {
    applicationId: "app-004",
    userId: "user-004",
    resumeId: "resume-004",
    jobMatchId: "match-004",
    appliedAt: "2026-02-19T14:00:00Z",
    finalATSScore: 91,
    applicationStatus: "applied",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-19T14:00:00Z" },
    ],
    interviewDetails: [],
    notes: "Application pending initial review",
  },
  {
    applicationId: "app-005",
    userId: "user-005",
    resumeId: "resume-005",
    jobMatchId: "match-001",
    appliedAt: "2026-02-21T11:20:00Z",
    finalATSScore: 85,
    applicationStatus: "rejected",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-21T11:20:00Z" },
      { status: "screening", updatedAt: "2026-02-23T10:15:00Z" },
      { status: "rejected", updatedAt: "2026-02-27T13:45:00Z", notes: "Not aligned with our tech stack" },
    ],
    interviewDetails: [],
    notes: "Candidate has strong Java background but limited React experience",
  },
  {
    applicationId: "app-006",
    userId: "user-006",
    resumeId: "resume-006",
    jobMatchId: "match-002",
    appliedAt: "2026-02-23T15:50:00Z",
    finalATSScore: 72,
    applicationStatus: "applied",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-23T15:50:00Z" },
    ],
    interviewDetails: [],
    notes: "Profile incomplete, follow up for additional information",
  },
  {
    applicationId: "app-007",
    userId: "user-007",
    resumeId: "resume-007",
    jobMatchId: "match-003",
    appliedAt: "2026-02-16T12:30:00Z",
    finalATSScore: 89,
    applicationStatus: "accepted",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-16T12:30:00Z" },
      { status: "screening", updatedAt: "2026-02-18T11:00:00Z" },
      { status: "interview", updatedAt: "2026-02-23T14:20:00Z" },
      { status: "offer", updatedAt: "2026-02-28T16:00:00Z" },
      { status: "accepted", updatedAt: "2026-03-04T09:45:00Z" },
    ],
    interviewDetails: [
      {
        round: 1,
        type: "technical",
        scheduledAt: "2026-02-23T13:00:00Z",
        completedAt: "2026-02-23T14:20:00Z",
        feedback: "Excellent technical expertise and problem-solving",
      },
    ],
    notes: "Candidate has accepted offer, scheduled for start on March 15",
  },
  {
    applicationId: "app-008",
    userId: "user-008",
    resumeId: "resume-008",
    jobMatchId: "match-004",
    appliedAt: "2026-02-24T10:00:00Z",
    finalATSScore: 93,
    applicationStatus: "screening",
    statusHistory: [
      { status: "applied", updatedAt: "2026-02-24T10:00:00Z", notes: "Strong PM background" },
      { status: "screening", updatedAt: "2026-03-01T14:30:00Z" },
    ],
    interviewDetails: [],
    notes: "Exciting candidate, potential for VP-level growth",
  },
];

const dummyATSScores: ATSScore[] = [
  {
    atsScoreId: "ats-001",
    userId: "user-001",
    resumeId: "resume-001",
    jobMatchId: "match-001",
    score: 94,
    calculatedAt: "2026-02-22T10:15:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 96,
      formatCompliance: 98,
      experienceMatch: 92,
      skillsMatch: 95,
      educationMatch: 88,
    },
    suggestions: [
      {
        category: "keywords",
        priority: "low",
        issue: "Missing 'system design' in headline",
        recommendation: "Add 'system design' to professional headline",
      },
    ],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-002",
    userId: "user-002",
    resumeId: "resume-002",
    jobMatchId: "match-002",
    score: 88,
    calculatedAt: "2026-02-20T09:45:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 90,
      formatCompliance: 92,
      experienceMatch: 85,
      skillsMatch: 88,
      educationMatch: 82,
    },
    suggestions: [
      {
        category: "skills",
        priority: "medium",
        issue: "No deep learning framework experience mentioned",
        recommendation: "Add TensorFlow or PyTorch experience to skills section",
      },
    ],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-003",
    userId: "user-003",
    resumeId: "resume-003",
    jobMatchId: "match-003",
    score: 96,
    calculatedAt: "2026-02-18T13:30:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 98,
      formatCompliance: 99,
      experienceMatch: 96,
      skillsMatch: 98,
      educationMatch: 90,
    },
    suggestions: [],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-004",
    userId: "user-004",
    resumeId: "resume-004",
    jobMatchId: "match-004",
    score: 91,
    calculatedAt: "2026-02-19T14:00:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 93,
      formatCompliance: 95,
      experienceMatch: 90,
      skillsMatch: 88,
      educationMatch: 85,
    },
    suggestions: [
      {
        category: "experience",
        priority: "low",
        issue: "Limited P&L management experience mentioned",
        recommendation: "Add more details about budget ownership",
      },
    ],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-005",
    userId: "user-005",
    resumeId: "resume-005",
    jobMatchId: "match-001",
    score: 85,
    calculatedAt: "2026-02-21T11:20:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 82,
      formatCompliance: 90,
      experienceMatch: 84,
      skillsMatch: 80,
      educationMatch: 88,
    },
    suggestions: [
      {
        category: "skills",
        priority: "high",
        issue: "Limited React experience for senior frontend role",
        recommendation: "Highlight any React projects or transition to React-focused role",
      },
    ],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-006",
    userId: "user-006",
    resumeId: "resume-006",
    jobMatchId: "match-002",
    score: 72,
    calculatedAt: "2026-02-23T15:50:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 75,
      formatCompliance: 88,
      experienceMatch: 68,
      skillsMatch: 70,
      educationMatch: 65,
    },
    suggestions: [
      {
        category: "experience",
        priority: "high",
        issue: "No machine learning project experience",
        recommendation: "Add ML projects or coursework",
      },
      {
        category: "skills",
        priority: "high",
        issue: "Missing technical skills for data scientist role",
        recommendation: "Add Python, SQL, ML libraries to skills",
      },
    ],
    passedThreshold: false,
  },
  {
    atsScoreId: "ats-007",
    userId: "user-007",
    resumeId: "resume-007",
    jobMatchId: "match-003",
    score: 89,
    calculatedAt: "2026-02-16T12:30:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 91,
      formatCompliance: 94,
      experienceMatch: 88,
      skillsMatch: 87,
      educationMatch: 82,
    },
    suggestions: [
      {
        category: "keywords",
        priority: "low",
        issue: "Could add 'infrastructure as code' keyword",
        recommendation: "Emphasize Terraform expertise more prominently",
      },
    ],
    passedThreshold: true,
  },
  {
    atsScoreId: "ats-008",
    userId: "user-008",
    resumeId: "resume-008",
    jobMatchId: "match-004",
    score: 93,
    calculatedAt: "2026-02-24T10:00:00Z",
    version: 1,
    scoreBreakdown: {
      keywordMatch: 95,
      formatCompliance: 97,
      experienceMatch: 92,
      skillsMatch: 90,
      educationMatch: 88,
    },
    suggestions: [],
    passedThreshold: true,
  },
];

export {
  dummyUsers,
  dummyResumes,
  dummyJobMatches,
  dummyApplications,
  dummyATSScores,
};
